table 'Markdown Content'
	lineageTag: 12345678-1234-1234-1234-123456789abc

	measure 'Sample Markdown' =
			VAR NL = UNICHAR(10)
			RETURN
			"# Welcome to Markdown Viewer :rocket:" & NL & NL &
			"This visual renders **Markdown** in Power BI!" & NL & NL &
			"## Features" & NL &
			"- Headers and formatting" & NL &
			"- Emoji support :heart: :star:" & NL &
			"- Code syntax highlighting"
		lineageTag: 87654321-4321-4321-4321-cba987654321

	column DummyColumn
		dataType: string
		lineageTag: abcdef12-3456-7890-abcd-ef1234567890
		summarizeBy: none
		sourceColumn: DummyColumn

		annotation SummarizationSetBy = Automatic

	partition 'Markdown Content' = m
		mode: import
		source =
				let
				    Source = #table({"DummyColumn"}, {{"Sample"}})
				in
				    Source